const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const {run,extract} = require('./helpers.cjs');
const base = path.join(__dirname,'../data/live-pages');
const planned=run('Build page list',[{data:fs.readFileSync(path.join(base,'1.html'),'utf8')}]);
assert.equal(planned.length,Number(fs.readFileSync(path.join(base,'count.txt'),'utf8')));
const pages=planned.map(p=>extract(fs.readFileSync(path.join(base,p.page+'.html'),'utf8')));
const timestamp=new Date().toISOString();
const refs={'Build page list':planned,'Configuration':[{timestamp}]};
const first=run('Compare snapshots',pages,refs)[0];
const second=run('Compare snapshots',pages,refs,{previous:first.snapshot})[0];
assert.equal(second.changes.length,0);
const changed=structuredClone(pages);changed[0].prices[0]='$1.00';
const third=run('Compare snapshots',changed,refs,{previous:first.snapshot})[0];
assert.equal(third.changes.length,1);
const result={timestamp,pages:planned.length,products:first.products.length,firstRunChanges:first.changes.length,identicalRunChanges:second.changes.length,simulatedPriceChanges:third.changes.length,scope:'Canlı HTML + workflow.json Code kaynakları ve selector testleri. n8n motoru, CSV düğümü ve SMTP yürütülmedi.'};
fs.writeFileSync(path.join(__dirname,'../live-check.json'),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result,null,2));
